//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmohamiWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        public static string AddRoleDescription {
            get {
                return ResourceManager.GetString("AddRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string AddRoleName {
            get {
                return ResourceManager.GetString("AddRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string AddRoleTitle {
            get {
                return ResourceManager.GetString("AddRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRoleTitle {
            get {
                return ResourceManager.GetString("EditRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string FooterAbout {
            get {
                return ResourceManager.GetString("FooterAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string FooterContacts {
            get {
                return ResourceManager.GetString("FooterContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on.
        /// </summary>
        public static string FooterFollowUs {
            get {
                return ResourceManager.GetString("FooterFollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIBE EMAIL.
        /// </summary>
        public static string FooterSubscribeEmail {
            get {
                return ResourceManager.GetString("FooterSubscribeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string IndexRoleTitle {
            get {
                return ResourceManager.GetString("IndexRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        public static string MenuCalender {
            get {
                return ResourceManager.GetString("MenuCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string MenuCase {
            get {
                return ResourceManager.GetString("MenuCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string MenuClients {
            get {
                return ResourceManager.GetString("MenuClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Case.
        /// </summary>
        public static string MenuCreateCase {
            get {
                return ResourceManager.GetString("MenuCreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string MenuCreateRole {
            get {
                return ResourceManager.GetString("MenuCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Case.
        /// </summary>
        public static string MenuDeleteCase {
            get {
                return ResourceManager.GetString("MenuDeleteCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Role.
        /// </summary>
        public static string MenuDeleteRole {
            get {
                return ResourceManager.GetString("MenuDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string MenuDocuments {
            get {
                return ResourceManager.GetString("MenuDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Case.
        /// </summary>
        public static string MenuEditCase {
            get {
                return ResourceManager.GetString("MenuEditCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string MenuEditRole {
            get {
                return ResourceManager.GetString("MenuEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string MenuFinance {
            get {
                return ResourceManager.GetString("MenuFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Access&amp;amp;Security.
        /// </summary>
        public static string MenuManageUserAccessandSecurity {
            get {
                return ResourceManager.GetString("MenuManageUserAccessandSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master User.
        /// </summary>
        public static string MenuMasterUser {
            get {
                return ResourceManager.GetString("MenuMasterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MenuReports {
            get {
                return ResourceManager.GetString("MenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string MenuRole {
            get {
                return ResourceManager.GetString("MenuRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub User.
        /// </summary>
        public static string MenuSubUser {
            get {
                return ResourceManager.GetString("MenuSubUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Case.
        /// </summary>
        public static string MenuViewCase {
            get {
                return ResourceManager.GetString("MenuViewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Role.
        /// </summary>
        public static string MenuViewRole {
            get {
                return ResourceManager.GetString("MenuViewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;amp; New.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
    }
}
