//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohamiWeb.OTPServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://itbsms.com/", ConfigurationName="OTPServiceReference.MessagingSoap")]
    public interface MessagingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.AuthenticationResult Http_AuthenticateUser(string username, string password, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AuthenticationResult> Http_AuthenticateUserAsync(string username, string password, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.AuthenticationResult AuthenticateUser(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AuthenticationResult> AuthenticateUserAsync(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_GetSmsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SMSStatusResult Http_GetSmsStatus(string username, string password, int customerId, string messageId, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_GetSmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SMSStatusResult> Http_GetSmsStatusAsync(string username, string password, int customerId, string messageId, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetSmsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SMSStatusResult GetSmsStatus(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetSmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SMSStatusResult> GetSmsStatusAsync(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SendingSMSResult Http_SendSMS(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Http_SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingSMSResult> Http_SendSMSAsync(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SendingSMSResult SendSMS(AlmohamiWeb.OTPServiceReference.SendingSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingSMSResult> SendSMSAsync(AlmohamiWeb.OTPServiceReference.SendingSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMSToDistributionList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult SendSMSToDistributionList(AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMSToDistributionList", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult> SendSMSToDistributionListAsync(AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAllDistributionLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.DistributionListsResult GetAllDistributionLists(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAllDistributionLists", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.DistributionListsResult> GetAllDistributionListsAsync(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMSToAdZoneLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult SendSMSToAdZoneLocation(AlmohamiWeb.OTPServiceReference.SendingAdZoneSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/SendSMSToAdZoneLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult> SendSMSToAdZoneLocationAsync(AlmohamiWeb.OTPServiceReference.SendingAdZoneSMSRequest sendingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAdZoneLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.DistributionListsResult GetAdZoneLocations(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAdZoneLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.DistributionListsResult> GetAdZoneLocationsAsync(AlmohamiWeb.OTPServiceReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAdZoneMessageStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.AdZoneMessageStatusResult GetAdZoneMessageStatus(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/GetAdZoneMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AdZoneMessageStatusResult> GetAdZoneMessageStatusAsync(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Get_Queued_Messages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseSendingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResult))]
        AlmohamiWeb.OTPServiceReference.Queued_Messages_Result Get_Queued_Messages(string username, string password, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itbsms.com/Get_Queued_Messages", ReplyAction="*")]
        System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.Queued_Messages_Result> Get_Queued_MessagesAsync(string username, string password, int customerId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AuthenticationResult : BaseResult {
        
        private int customerIdField;
        
        private decimal netPointsField;
        
        private System.DateTime balanceExpirationDateField;
        
        private string[] sendersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime BalanceExpirationDate {
            get {
                return this.balanceExpirationDateField;
            }
            set {
                this.balanceExpirationDateField = value;
                this.RaisePropertyChanged("BalanceExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Senders {
            get {
                return this.sendersField;
            }
            set {
                this.sendersField = value;
                this.RaisePropertyChanged("Senders");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Queued_Messages_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdZoneMessageStatusResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistributionListsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseSendingResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSStatusResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class BaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingAdZoneSMSRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public abstract partial class BaseSendingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SoapUser userField;
        
        private string senderTextField;
        
        private string messageBodyField;
        
        private System.Nullable<System.DateTime> defDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SoapUser User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SenderText {
            get {
                return this.senderTextField;
            }
            set {
                this.senderTextField = value;
                this.RaisePropertyChanged("SenderText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
                this.RaisePropertyChanged("MessageBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> DefDate {
            get {
                return this.defDateField;
            }
            set {
                this.defDateField = value;
                this.RaisePropertyChanged("DefDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SoapUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private int customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingAdZoneSMSRequest : BaseSendingRequest {
        
        private System.Guid distributionListGuidField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private DayOfWeek[] sendingDaysField;
        
        private byte[] sendingHoursField;
        
        private int recipientsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
                this.RaisePropertyChanged("DistributionListGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public DayOfWeek[] SendingDays {
            get {
                return this.sendingDaysField;
            }
            set {
                this.sendingDaysField = value;
                this.RaisePropertyChanged("SendingDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] SendingHours {
            get {
                return this.sendingHoursField;
            }
            set {
                this.sendingHoursField = value;
                this.RaisePropertyChanged("SendingHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int RecipientsCount {
            get {
                return this.recipientsCountField;
            }
            set {
                this.recipientsCountField = value;
                this.RaisePropertyChanged("RecipientsCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum DayOfWeek {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingDistributionListSMSRequest : BaseSendingRequest {
        
        private System.Guid distributionListGuidField;
        
        private bool sendToAllTheDistributionListNumbersField;
        
        private int countField;
        
        private int offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
                this.RaisePropertyChanged("DistributionListGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool SendToAllTheDistributionListNumbers {
            get {
                return this.sendToAllTheDistributionListNumbersField;
            }
            set {
                this.sendToAllTheDistributionListNumbersField = value;
                this.RaisePropertyChanged("SendToAllTheDistributionListNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingSMSRequest : BaseSendingRequest {
        
        private bool isBlinkField;
        
        private bool isFlashField;
        
        private string recipientNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsBlink {
            get {
                return this.isBlinkField;
            }
            set {
                this.isBlinkField = value;
                this.RaisePropertyChanged("IsBlink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsFlash {
            get {
                return this.isFlashField;
            }
            set {
                this.isFlashField = value;
                this.RaisePropertyChanged("IsFlash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecipientNumbers {
            get {
                return this.recipientNumbersField;
            }
            set {
                this.recipientNumbersField = value;
                this.RaisePropertyChanged("RecipientNumbers");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AdZoneMsgStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campaignNameField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private AdZoneMsgtate statusField;
        
        private AdZoneMsgCompletionType completionTypeField;
        
        private System.DateTime completionTimeField;
        
        private int partsPerMessageField;
        
        private int totalRecipientsLimitField;
        
        private int totalMessagePartsLimitField;
        
        private int totalBillableRecipientsCountField;
        
        private int totalBillableMessagePartsField;
        
        private System.Guid messageGuidField;
        
        private int sentProviderMessageIdField;
        
        private System.DateTime createdOnUtcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CampaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
                this.RaisePropertyChanged("CampaignName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AdZoneMsgtate Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AdZoneMsgCompletionType CompletionType {
            get {
                return this.completionTypeField;
            }
            set {
                this.completionTypeField = value;
                this.RaisePropertyChanged("CompletionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CompletionTime {
            get {
                return this.completionTimeField;
            }
            set {
                this.completionTimeField = value;
                this.RaisePropertyChanged("CompletionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PartsPerMessage {
            get {
                return this.partsPerMessageField;
            }
            set {
                this.partsPerMessageField = value;
                this.RaisePropertyChanged("PartsPerMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TotalRecipientsLimit {
            get {
                return this.totalRecipientsLimitField;
            }
            set {
                this.totalRecipientsLimitField = value;
                this.RaisePropertyChanged("TotalRecipientsLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int TotalMessagePartsLimit {
            get {
                return this.totalMessagePartsLimitField;
            }
            set {
                this.totalMessagePartsLimitField = value;
                this.RaisePropertyChanged("TotalMessagePartsLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int TotalBillableRecipientsCount {
            get {
                return this.totalBillableRecipientsCountField;
            }
            set {
                this.totalBillableRecipientsCountField = value;
                this.RaisePropertyChanged("TotalBillableRecipientsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TotalBillableMessageParts {
            get {
                return this.totalBillableMessagePartsField;
            }
            set {
                this.totalBillableMessagePartsField = value;
                this.RaisePropertyChanged("TotalBillableMessageParts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Guid MessageGuid {
            get {
                return this.messageGuidField;
            }
            set {
                this.messageGuidField = value;
                this.RaisePropertyChanged("MessageGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int SentProviderMessageId {
            get {
                return this.sentProviderMessageIdField;
            }
            set {
                this.sentProviderMessageIdField = value;
                this.RaisePropertyChanged("SentProviderMessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime CreatedOnUtc {
            get {
                return this.createdOnUtcField;
            }
            set {
                this.createdOnUtcField = value;
                this.RaisePropertyChanged("CreatedOnUtc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum AdZoneMsgtate {
        
        /// <remarks/>
        Preprocessing,
        
        /// <remarks/>
        QueuedForCreation,
        
        /// <remarks/>
        CreatedButNotInitiated,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Finalizing,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        CompletedAndBilled,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum AdZoneMsgCompletionType {
        
        /// <remarks/>
        NotYetCompleted,
        
        /// <remarks/>
        TargetMessagePartsLimitReached,
        
        /// <remarks/>
        EndDateReached,
        
        /// <remarks/>
        StoppedByUser,
        
        /// <remarks/>
        StoppedByAdmin,
        
        /// <remarks/>
        TerminatedByAdmin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class DistributionListItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.Guid guidField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("TotalCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSNumbers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] sentNumbersField;
        
        private string[] queuedNumbersField;
        
        private string[] rejectedNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] SentNumbers {
            get {
                return this.sentNumbersField;
            }
            set {
                this.sentNumbersField = value;
                this.RaisePropertyChanged("SentNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] QueuedNumbers {
            get {
                return this.queuedNumbersField;
            }
            set {
                this.queuedNumbersField = value;
                this.RaisePropertyChanged("QueuedNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
                this.RaisePropertyChanged("RejectedNumbers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSCounters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sentCountField;
        
        private int queuedCountField;
        
        private int rejectedCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SentCount {
            get {
                return this.sentCountField;
            }
            set {
                this.sentCountField = value;
                this.RaisePropertyChanged("SentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int QueuedCount {
            get {
                return this.queuedCountField;
            }
            set {
                this.queuedCountField = value;
                this.RaisePropertyChanged("QueuedCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RejectedCount {
            get {
                return this.rejectedCountField;
            }
            set {
                this.rejectedCountField = value;
                this.RaisePropertyChanged("RejectedCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class Queued_Messages_Result : BaseResult {
        
        private int queuedCountField;
        
        private string[] messagesIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int QueuedCount {
            get {
                return this.queuedCountField;
            }
            set {
                this.queuedCountField = value;
                this.RaisePropertyChanged("QueuedCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] MessagesIds {
            get {
                return this.messagesIdsField;
            }
            set {
                this.messagesIdsField = value;
                this.RaisePropertyChanged("MessagesIds");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AdZoneMessageStatusResult : BaseResult {
        
        private AdZoneMsgStatus adZoneMsgStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AdZoneMsgStatus AdZoneMsgStatus {
            get {
                return this.adZoneMsgStatusField;
            }
            set {
                this.adZoneMsgStatusField = value;
                this.RaisePropertyChanged("AdZoneMsgStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class DistributionListsResult : BaseResult {
        
        private DistributionListItem[] distributionListsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DistributionListItem[] DistributionLists {
            get {
                return this.distributionListsField;
            }
            set {
                this.distributionListsField = value;
                this.RaisePropertyChanged("DistributionLists");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class BaseSendingResult : BaseResult {
        
        private decimal netPointsField;
        
        private System.Guid messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingDistributionListSMSResult : BaseSendingResult {
        
        private string distributionListNameField;
        
        private System.Guid distributionListGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DistributionListName {
            get {
                return this.distributionListNameField;
            }
            set {
                this.distributionListNameField = value;
                this.RaisePropertyChanged("DistributionListName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
                this.RaisePropertyChanged("DistributionListGuid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingSMSResult : BaseSendingResult {
        
        private string[] rejectedNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
                this.RaisePropertyChanged("RejectedNumbers");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSStatusResult : BaseResult {
        
        private decimal netPointsField;
        
        private SMSCounters countersField;
        
        private SMSNumbers numbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SMSCounters Counters {
            get {
                return this.countersField;
            }
            set {
                this.countersField = value;
                this.RaisePropertyChanged("Counters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SMSNumbers Numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
                this.RaisePropertyChanged("Numbers");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagingSoapChannel : AlmohamiWeb.OTPServiceReference.MessagingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingSoapClient : System.ServiceModel.ClientBase<AlmohamiWeb.OTPServiceReference.MessagingSoap>, AlmohamiWeb.OTPServiceReference.MessagingSoap {
        
        public MessagingSoapClient() {
        }
        
        public MessagingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlmohamiWeb.OTPServiceReference.AuthenticationResult Http_AuthenticateUser(string username, string password, int customerId) {
            return base.Channel.Http_AuthenticateUser(username, password, customerId);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AuthenticationResult> Http_AuthenticateUserAsync(string username, string password, int customerId) {
            return base.Channel.Http_AuthenticateUserAsync(username, password, customerId);
        }
        
        public AlmohamiWeb.OTPServiceReference.AuthenticationResult AuthenticateUser(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.AuthenticateUser(user);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AuthenticationResult> AuthenticateUserAsync(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.AuthenticateUserAsync(user);
        }
        
        public AlmohamiWeb.OTPServiceReference.SMSStatusResult Http_GetSmsStatus(string username, string password, int customerId, string messageId, bool detailed) {
            return base.Channel.Http_GetSmsStatus(username, password, customerId, messageId, detailed);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SMSStatusResult> Http_GetSmsStatusAsync(string username, string password, int customerId, string messageId, bool detailed) {
            return base.Channel.Http_GetSmsStatusAsync(username, password, customerId, messageId, detailed);
        }
        
        public AlmohamiWeb.OTPServiceReference.SMSStatusResult GetSmsStatus(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId, bool detailed) {
            return base.Channel.GetSmsStatus(user, messageId, detailed);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SMSStatusResult> GetSmsStatusAsync(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId, bool detailed) {
            return base.Channel.GetSmsStatusAsync(user, messageId, detailed);
        }
        
        public AlmohamiWeb.OTPServiceReference.SendingSMSResult Http_SendSMS(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash) {
            return base.Channel.Http_SendSMS(username, password, customerId, senderText, messageBody, recipientNumbers, defDate, isBlink, isFlash);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingSMSResult> Http_SendSMSAsync(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash) {
            return base.Channel.Http_SendSMSAsync(username, password, customerId, senderText, messageBody, recipientNumbers, defDate, isBlink, isFlash);
        }
        
        public AlmohamiWeb.OTPServiceReference.SendingSMSResult SendSMS(AlmohamiWeb.OTPServiceReference.SendingSMSRequest sendingRequest) {
            return base.Channel.SendSMS(sendingRequest);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingSMSResult> SendSMSAsync(AlmohamiWeb.OTPServiceReference.SendingSMSRequest sendingRequest) {
            return base.Channel.SendSMSAsync(sendingRequest);
        }
        
        public AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult SendSMSToDistributionList(AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSRequest sendingRequest) {
            return base.Channel.SendSMSToDistributionList(sendingRequest);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult> SendSMSToDistributionListAsync(AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSRequest sendingRequest) {
            return base.Channel.SendSMSToDistributionListAsync(sendingRequest);
        }
        
        public AlmohamiWeb.OTPServiceReference.DistributionListsResult GetAllDistributionLists(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.GetAllDistributionLists(user);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.DistributionListsResult> GetAllDistributionListsAsync(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.GetAllDistributionListsAsync(user);
        }
        
        public AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult SendSMSToAdZoneLocation(AlmohamiWeb.OTPServiceReference.SendingAdZoneSMSRequest sendingRequest) {
            return base.Channel.SendSMSToAdZoneLocation(sendingRequest);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.SendingDistributionListSMSResult> SendSMSToAdZoneLocationAsync(AlmohamiWeb.OTPServiceReference.SendingAdZoneSMSRequest sendingRequest) {
            return base.Channel.SendSMSToAdZoneLocationAsync(sendingRequest);
        }
        
        public AlmohamiWeb.OTPServiceReference.DistributionListsResult GetAdZoneLocations(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.GetAdZoneLocations(user);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.DistributionListsResult> GetAdZoneLocationsAsync(AlmohamiWeb.OTPServiceReference.SoapUser user) {
            return base.Channel.GetAdZoneLocationsAsync(user);
        }
        
        public AlmohamiWeb.OTPServiceReference.AdZoneMessageStatusResult GetAdZoneMessageStatus(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId) {
            return base.Channel.GetAdZoneMessageStatus(user, messageId);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.AdZoneMessageStatusResult> GetAdZoneMessageStatusAsync(AlmohamiWeb.OTPServiceReference.SoapUser user, System.Guid messageId) {
            return base.Channel.GetAdZoneMessageStatusAsync(user, messageId);
        }
        
        public AlmohamiWeb.OTPServiceReference.Queued_Messages_Result Get_Queued_Messages(string username, string password, int customerId) {
            return base.Channel.Get_Queued_Messages(username, password, customerId);
        }
        
        public System.Threading.Tasks.Task<AlmohamiWeb.OTPServiceReference.Queued_Messages_Result> Get_Queued_MessagesAsync(string username, string password, int customerId) {
            return base.Channel.Get_Queued_MessagesAsync(username, password, customerId);
        }
    }
}
